export const pratosPrincipais = {
  feijoada: {
    nome: "Feijoada Completa",
    imagem: require("../../assets/images/img_pratos_principais/feijoada-Completa.jpg"),
    descricao: "Prato tradicional brasileiro à base de feijão preto e carnes.",
    ingredientes: [
      { nome: "Feijão preto", quantidade: "500g" },
      { nome: "Carne seca", quantidade: "300g" },
      { nome: "Linguiça", quantidade: "200g" },
      { nome: "Bacon", quantidade: "100g" },
      { nome: "Cebola", quantidade: "1 unidade" },
      { nome: "Alho", quantidade: "3 dentes" },
      { nome: "Louro", quantidade: "2 folhas" },
    ],
    preparo: "Deixe o feijão de molho por 12h. Cozinhe as carnes separadamente. Refogue alho e cebola, junte o feijão, depois as carnes. Cozinhe por 1h30 e sirva com arroz branco e couve.",
  },
  moqueca: {
    nome: "Moqueca de Peixe",
    imagem: require("../../assets/images/img_pratos_principais/Moqueca_peixe.jpg"),
    descricao: "Deliciosa moqueca com peixe fresco e leite de coco.",
    ingredientes: [
      { nome: "Peixe branco", quantidade: "1kg" },
      { nome: "Leite de coco", quantidade: "400ml" },
      { nome: "Azeite de dendê", quantidade: "50ml" },
      { nome: "Tomate", quantidade: "3 unidades" },
      { nome: "Pimentão", quantidade: "2 unidades" },
      { nome: "Cebola", quantidade: "1 unidade" },
      { nome: "Coentro", quantidade: "a gosto" },
    ],
    preparo: "Tempere o peixe com sal e limão. Refogue cebola, tomate e pimentão. Coloque o peixe, cubra com leite de coco e azeite de dendê. Cozinhe por 20 minutos. Finalize com coentro.",
  },
  churrasco: {
    nome: "Churrasco",
    imagem: require("../../assets/images/img_pratos_principais/churrasco.png"),
    descricao: "Carnes grelhadas ao estilo brasileiro.",
    ingredientes: [
      { nome: "Carne bovina", quantidade: "1kg" },
      { nome: "Sal grosso", quantidade: "a gosto" },
    ],
    preparo: "Tempere a carne com sal grosso e grelhe até o ponto desejado.",
  },
  galinhada: {
    nome: "Galinhada",
    imagem: require("../../assets/images/img_pratos_principais/galinhada.jpg"),
    descricao: "Arroz com frango típico das festas e encontros familiares.",
    ingredientes: [
      { nome: "Frango", quantidade: "1kg" },
      { nome: "Arroz", quantidade: "2 xícaras" },
      { nome: "Cebola", quantidade: "1 unidade" },
      { nome: "Alho", quantidade: "2 dentes" },
      { nome: "Tomate", quantidade: "2 unidades" },
      { nome: "Cheiro-verde", quantidade: "a gosto" },
    ],
    preparo: "Refogue o frango com alho e cebola, adicione os tomates e cozinhe. Acrescente o arroz e cozinhe até secar. Finalize com cheiro-verde.",
  },
  bobozinho: {
    nome: "Bobó de Camarão",
    imagem: require("../../assets/images/img_pratos_principais/Bobó_de_Camarão.jpg"),
    descricao: "Delicioso prato com camarões e creme de mandioca.",
    ingredientes: [
      { nome: "Camarão", quantidade: "500g" },
      { nome: "Mandioca", quantidade: "400g" },
      { nome: "Leite de coco", quantidade: "200ml" },
      { nome: "Azeite de dendê", quantidade: "50ml" },
      { nome: "Cebola", quantidade: "1 unidade" },
      { nome: "Alho", quantidade: "2 dentes" },
      { nome: "Coentro", quantidade: "a gosto" },
    ],
    preparo: "Cozinhe a mandioca e bata até virar creme. Refogue camarões com alho e cebola. Misture o creme, acrescente leite de coco e azeite de dendê e cozinhe por 10 minutos.",
  },
  estrogonofe: {
    nome: "Estrogonofe de Carne",
    imagem: require("../../assets/images/img_pratos_principais/Estrogonofe_Carne.png"),
    descricao: "Clássico estrogonofe cremoso com carne e molho especial.",
    ingredientes: [
      { nome: "Carne bovina", quantidade: "500g" },
      { nome: "Creme de leite", quantidade: "1 caixinha" },
      { nome: "Molho de tomate", quantidade: "200ml" },
      { nome: "Cebola", quantidade: "1 unidade" },
      { nome: "Mostarda", quantidade: "1 colher de sopa" },
    ],
    preparo: "Refogue a carne com cebola, adicione o molho de tomate e mostarda. Cozinhe por 10 minutos e finalize com creme de leite.",
  },
  escondidinho: {
    nome: "Escondidinho de Carne Seca",
    imagem: require("../../assets/images/img_pratos_principais/Escondidinho_de_Carne_Seca.png"),
    descricao: "Purê de mandioca com recheio de carne seca gratinado.",
    ingredientes: [
      { nome: "Mandioca", quantidade: "500g" },
      { nome: "Carne seca desfiada", quantidade: "300g" },
      { nome: "Requeijão", quantidade: "200g" },
      { nome: "Queijo ralado", quantidade: "a gosto" },
      { nome: "Cebola", quantidade: "1 unidade" },
      { nome: "Alho", quantidade: "2 dentes" },
    ],
    preparo: "Cozinhe a mandioca e faça purê. Refogue a carne seca com cebola e alho. Monte camadas com purê e carne, finalize com queijo e leve ao forno até gratinar.",
  },
};

